on:
  push:
    branches:
      - main # Specify the branch you want to trigger this action on

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    name: Notify Slack on Push
    steps:
      - name: Send notification to Slack
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": "New push to repository",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "A new push has been made to the repository."
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "Branch: *${{ github.ref }}*\nCommit: *${{ github.sha }}*\nBy: *${{ github.actor }}*"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
